// This file is part of paas_manager.
// Copyright (C) 2024 RokctAI
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String imageAppLogo = 'assets/image/app_logo.png';
  static const String imageKfc = 'assets/image/kfc.png';
  static const String imageLogo = 'assets/image/logo.png';
  static const String imageManager = 'assets/image/manager.png';
  static const String imageMarker = 'assets/image/marker.png';
  static const String imageNoNotification = 'assets/image/noNotification.png';
  static const String imageNoOrders = 'assets/image/no_orders.png';
  static const String imageNoProduct = 'assets/image/noProduct.png';
  static const String imageSplash = 'assets/image/splash.png';
  static const String lottieClose = 'assets/lottie/close.json';
  static const String lottiePin = 'assets/lottie/pin.json';
  static const String lottieProcessing = 'assets/lottie/processing.json';
  static const String svgDelivery = 'assets/svg/delivery.svg';
  static const String svgFoodyman = 'assets/svg/foodyman.svg';
  static const String svgHome = 'assets/svg/home.svg';
  static const String svgLogoWhite = 'assets/svg/logoWhite.svg';
  static const String svgMenu = 'assets/svg/menu.svg';
  static const String svgNoHome = 'assets/svg/noHome.svg';

}
