// GENERATED FILE - DO NOT EDIT BY HAND.
//
// Generated by RokctAI/shared-workflows scripts/tour/merge_fragments.py from
// this app's tour/app.tour.yaml plus the tour fragments shipped by the
// composed SDKs (each SDK's templates/tour/<sdk>.tour.yaml). CI regenerates
// it on every guided-tour run; the committed copy exists so the repo
// analyzes and compiles without running the merge first.
//
// ignore_for_file: unused_import, always_specify_types, avoid_redundant_argument_values
// ignore_for_file: unawaited_futures, use_build_context_synchronously
// ignore_for_file: implementation_imports, directives_ordering, depend_on_referenced_packages

import 'package:auto_route/auto_route.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:auth_sdk/src/common/application/auth/auth.dart';
import 'package:base_sdk/src/models/response/languages_response.dart';
import 'package:base_sdk/src/services/app_helpers.dart';
import 'package:base_sdk/src/services/local_storage.dart';
import 'package:base_sdk/src/services/tr_keys.dart';
import 'package:comms_sdk/src/common/presentation/pages/setting/language_page.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:merchants_sdk/src/manager/application/main/main_provider.dart';
import 'package:merchants_sdk/src/manager/application/pos_cart/pos_cart_provider.dart';
import 'package:remixicon/remixicon.dart';

typedef TourAction = Future<void> Function(
    WidgetTester tester, StackRouter router);

class TourStep {
  const TourStep(this.key, this.settleMs, this.screenshot, this.action);

  final String key;
  final int settleMs;

  /// False for steps that only perform an action (no still captured).
  final bool screenshot;
  final TourAction action;
}

/// Runs once before the app is launched.
Future<void> tourSetup() async {
  // Pre-seed the language so the first-run language picker can never
  // block the tour behind a non-dismissible modal (the backend may
  // advertise several languages). LocalStorage.init() is idempotent -
  // app.main() calls it again.
  await LocalStorage.init();
  if (LocalStorage.getLanguage() == null) {
    await LocalStorage.setLanguageData(LanguageData(
      id: '1',
      title: 'English',
      locale: 'en',
      backward: false,
      isDefault: true,
      active: true,
    ));
    await LocalStorage.setLanguageSelected(true);
    await LocalStorage.setLangLtr(false);
  }
}

final List<TourStep> tourSteps = <TourStep>[
  TourStep('welcome', 12000, true, (WidgetTester tester, StackRouter router) async {
    // wait: settle only.
  }),
  TourStep('auth_login', 5000, true, (WidgetTester tester, StackRouter router) async {
    // Land on /login (the welcome screen), then open the login sheet the
    // way a user does - via its Login button.
    router.replaceNamed('/login');
    await Future<void>.delayed(const Duration(seconds: 3));
    await tester.tap(
      find.text(AppHelpers.getTranslation(TrKeys.login)).first,
      warnIfMissed: false,
    );
  }),
  TourStep('auth_register', 5000, true, (WidgetTester tester, StackRouter router) async {
    // Close the login sheet, then open the register sheet from the
    // welcome screen's Register button.
    final NavigatorState navigator =
        tester.state(find.byType(Navigator).first);
    if (navigator.canPop()) {
      navigator.pop();
      await Future<void>.delayed(const Duration(seconds: 2));
    }
    await tester.tap(
      find.text(AppHelpers.getTranslation(TrKeys.register)).first,
      warnIfMissed: false,
    );
  }),
  TourStep('auth_reset_password', 5000, true, (WidgetTester tester, StackRouter router) async {
    // Close the register sheet, reopen the login sheet, then tap
    // "Forgot password" - its handler swaps the login sheet for the
    // reset-password sheet, exactly the path a user takes.
    final NavigatorState navigator =
        tester.state(find.byType(Navigator).first);
    if (navigator.canPop()) {
      navigator.pop();
      await Future<void>.delayed(const Duration(seconds: 2));
    }
    await tester.tap(
      find.text(AppHelpers.getTranslation(TrKeys.login)).first,
      warnIfMissed: false,
    );
    await Future<void>.delayed(const Duration(seconds: 3));
    await tester.tap(
      find.text(AppHelpers.getTranslation(TrKeys.forgotPassword)).first,
      warnIfMissed: false,
    );
  }),
  TourStep('auth_back_to_login', 3000, false, (WidgetTester tester, StackRouter router) async {
    final NavigatorState navigator =
        tester.state(find.byType(Navigator).first);
    // Bounded: at most one sheet is open, but stay safe against strays.
    for (int i = 0; i < 5 && navigator.canPop(); i++) {
      navigator.pop();
      await Future<void>.delayed(const Duration(milliseconds: 500));
    }
    router.replaceNamed('/login');
  }),
  TourStep('demo_sign_in', 6000, false, (WidgetTester tester, StackRouter router) async {
    final Element element = tester.element(find.byType(Navigator).first);
    final ProviderContainer container =
        ProviderScope.containerOf(element, listen: false);
    // loginProvider is autoDispose: hold a subscription so the notifier
    // survives between the field writes and the login call.
    final ProviderSubscription<dynamic> subscription =
        container.listen(loginProvider, (_, __) {});
    try {
      final login = container.read(loginProvider.notifier);
      login.setEmail('demo.student@example.com');
      login.setPassword('demo-learners-2026');
      // MockAuthRepository accepts any credentials. The timeout guards the
      // post-session FCM sync, which can stall on an emulator - navigation
      // to the demo landing happens before it, so a timeout is harmless.
      await login
          .login(element)
          .timeout(const Duration(seconds: 45), onTimeout: () {});
    } finally {
      subscription.close();
    }
  }),
  TourStep('back_to_login', 4000, false, (WidgetTester tester, StackRouter router) async {
    LocalStorage.logout();
    router.replaceNamed('/login');
  }),
  TourStep('manager_sign_in', 6000, false, (WidgetTester tester, StackRouter router) async {
    final Element element = tester.element(find.byType(Navigator).first);
    final ProviderContainer container =
        ProviderScope.containerOf(element, listen: false);
    // loginProvider is autoDispose: hold a subscription so the notifier
    // survives between the field writes and the login call.
    final ProviderSubscription<dynamic> subscription =
        container.listen(loginProvider, (_, __) {});
    try {
      final login = container.read(loginProvider.notifier);
      login.setEmail('manager@demo.rokct.ai');
      login.setPassword('demo-managers-2026');
      // MockAuthRepository accepts any credentials. The timeout guards the
      // post-session FCM sync, which can stall on an emulator - navigation
      // to the demo landing happens before it, so a timeout is harmless.
      await login
          .login(element)
          .timeout(const Duration(seconds: 45), onTimeout: () {});
    } finally {
      subscription.close();
    }
  }),
  TourStep('manager_home', 10000, false, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/main');
  }),
  TourStep('pos_scan', 8000, true, (WidgetTester tester, StackRouter router) async {
    // Select the POS tab (index 0) explicitly - an earlier fragment may
    // have left another tab selected, and mainProvider's selection
    // persists across routes.
    router.replaceNamed('/main');
    await Future<void>.delayed(const Duration(seconds: 3));
    final Element element = tester.element(find.byType(Navigator).first);
    final ProviderContainer container =
        ProviderScope.containerOf(element, listen: false);
    container.read(mainProvider.notifier).selectIndex(0);
  }),
  TourStep('pos_cart', 6000, true, (WidgetTester tester, StackRouter router) async {
    // Demo build: the barcode lane resolves through this SDK's
    // MockProductsRepository ("Demo Product", R150.00), zero backend
    // contact - the same path a real scan takes.
    final Element element = tester.element(find.byType(Navigator).first);
    final ProviderContainer container =
        ProviderScope.containerOf(element, listen: false);
    await container
        .read(posCartProvider.notifier)
        .addByBarcode('6001067890123');
    container.read(posCartProvider.notifier).increment(0);
  }),
  TourStep('pos_checkout', 8000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/pos-checkout');
  }),
  TourStep('restaurant_hub', 8000, true, (WidgetTester tester, StackRouter router) async {
    // Land the manager home shell and select the restaurant tab (index 4
    // since merchants_sdk 1.14.0 - POS till 0, order queue 1, kitchen 2,
    // foods 3) through the shell's own mainProvider, the same state the
    // bottom-navigation buttons drive. Route first: an earlier fragment
    // may have left the app elsewhere, and mainProvider's selection
    // persists across routes.
    //
    // The tab is preload: false in the shell's IndexedStack, so selecting
    // it is what first builds RestaurantPage - whose initState fetches
    // the shop through SellerShopRepositoryFacade. In demo builds that is
    // this SDK's DemoSellerShopRepository (see the demo-grounding note at
    // the top of this file), so the header renders with the demo shop's
    // name and rating rather than empty; the rows below it carry their
    // own isDemo subtitles. The settle covers that first fetch.
    router.replaceNamed('/main');
    await Future<void>.delayed(const Duration(seconds: 3));
    final Element element = tester.element(find.byType(Navigator).first);
    final ProviderContainer container =
        ProviderScope.containerOf(element, listen: false);
    container.read(mainProvider.notifier).selectIndex(4);
  }),
  TourStep('sync_issues', 6000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/sync-issues');
  }),
  TourStep('menu', 8000, true, (WidgetTester tester, StackRouter router) async {
    // Land the manager home shell, then select the foods tab (index 3
    // since merchants_sdk 1.14.0 - POS till 0, order queue 1, kitchen 2;
    // this fragment had gone stale at 1 when the POS-first shift moved
    // foods to 2) through the shell's own mainProvider - the same state
    // the bottom navigation buttons drive. Route first: an earlier
    // fragment may have left the app elsewhere.
    router.replaceNamed('/main');
    await Future<void>.delayed(const Duration(seconds: 3));
    final Element element = tester.element(find.byType(Navigator).first);
    final ProviderContainer container =
        ProviderScope.containerOf(element, listen: false);
    container.read(mainProvider.notifier).selectIndex(3);
  }),
  TourStep('add_product', 6000, true, (WidgetTester tester, StackRouter router) async {
    // FoodsPage's own "+ New product" header button opens the
    // create-product modal (foods_page.dart's _newButton dispatches by
    // inner tab, foods sub-tab 0 - the shell FAB's old rule, moved
    // in-page in products_sdk 1.6.0). Both its wide (labelled) and
    // phone (icon ring) dresses carry Remix.add_line, the only
    // Remix.add_line on this screen; tolerant tap anyway.
    await tester.tap(
      find.byIcon(Remix.add_line).first,
      warnIfMissed: false,
    );
  }),
  TourStep('add_product_close', 3000, false, (WidgetTester tester, StackRouter router) async {
    final NavigatorState navigator =
        tester.state(find.byType(Navigator).first);
    // Bounded: at most the one modal sheet is open.
    for (int i = 0; i < 3 && navigator.canPop(); i++) {
      navigator.pop();
      await Future<void>.delayed(const Duration(milliseconds: 500));
    }
  }),
  TourStep('order_queue', 8000, true, (WidgetTester tester, StackRouter router) async {
    // Land the manager home shell and select the order-queue tab
    // (index 1 - index 0 is the POS till since merchants_sdk 1.12.0)
    // explicitly - an earlier fragment may have left another tab
    // selected, and mainProvider's selection persists across routes.
    router.replaceNamed('/main');
    await Future<void>.delayed(const Duration(seconds: 3));
    final Element element = tester.element(find.byType(Navigator).first);
    final ProviderContainer container =
        ProviderScope.containerOf(element, listen: false);
    container.read(mainProvider.notifier).selectIndex(1);
  }),
  TourStep('order_history', 6000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/order-history');
  }),
  TourStep('kitchen_queue', 8000, true, (WidgetTester tester, StackRouter router) async {
    // Land the manager home shell and select the Kitchen tab (index 2
    // since merchants_sdk 1.14.0 - the POS till is 0, the order queue 1)
    // explicitly - an earlier fragment may have left another tab
    // selected, and mainProvider's selection persists across routes.
    router.replaceNamed('/main');
    await Future<void>.delayed(const Duration(seconds: 3));
    final Element element = tester.element(find.byType(Navigator).first);
    final ProviderContainer container =
        ProviderScope.containerOf(element, listen: false);
    container.read(mainProvider.notifier).selectIndex(2);
  }),
  TourStep('comms_language', 6000, true, (WidgetTester tester, StackRouter router) async {
    // Open the language sheet the way the app's own screens do: the same
    // AppHelpers.showCustomModalBottomSheet call auth's login page and
    // marketplace's profile use for EmbeddedWidgets.I.languageScreen.
    // LanguageScreen is comms_sdk's own widget; in demo builds its list
    // comes from MockSettingsRepository.getLanguages().
    final BuildContext sheetContext =
        tester.element(find.byType(Navigator).first);
    AppHelpers.showCustomModalBottomSheet(
      context: sheetContext,
      modal: LanguageScreen(
        onSave: () =>
            Navigator.of(sheetContext, rootNavigator: true).pop(),
      ),
      isDarkMode: false,
    );
  }),
  TourStep('comms_language_close', 3000, false, (WidgetTester tester, StackRouter router) async {
    // Tolerant: pop only when the sheet from the step above is actually
    // on screen, so this can never pop a real app route.
    if (find.byType(LanguageScreen).evaluate().isNotEmpty) {
      final NavigatorState navigator =
          tester.state(find.byType(Navigator).first);
      if (navigator.canPop()) {
        navigator.pop();
      }
    }
  }),
  TourStep('revenue_income', 8000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/income');
  }),
  TourStep('subscriptions_plans', 8000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/subscriptions');
  }),
  TourStep('productivity_tasks', 7000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/tasks');
  }),
  TourStep('calc_keypad', 6000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/calc');
  }),
];
