// GENERATED FILE - DO NOT EDIT BY HAND.
//
// Generated by RokctAI/shared-workflows scripts/tour/merge_fragments.py from
// this app's tour/app.tour.yaml plus the tour fragments shipped by the
// composed SDKs (each SDK's templates/tour/<sdk>.tour.yaml). CI regenerates
// it on every guided-tour run; the committed copy exists so the repo
// analyzes and compiles without running the merge first.
//
// ignore_for_file: unused_import, always_specify_types, avoid_redundant_argument_values
// ignore_for_file: unawaited_futures, use_build_context_synchronously
// ignore_for_file: implementation_imports, directives_ordering, depend_on_referenced_packages

import 'package:auto_route/auto_route.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:auth_sdk/src/common/application/auth/auth.dart';
import 'package:base_sdk/src/database/app_database.dart';
import 'package:base_sdk/src/models/response/languages_response.dart';
import 'package:base_sdk/src/presentation/adaptive/planes.dart';
import 'package:base_sdk/src/services/app_helpers.dart';
import 'package:base_sdk/src/services/local_storage.dart';
import 'package:base_sdk/src/services/tr_keys.dart';
import 'package:comms_sdk/src/common/presentation/pages/setting/language_page.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:merchants_sdk/src/manager/application/main/main_provider.dart';
import 'package:merchants_sdk/src/manager/application/pos_cart/pos_cart_provider.dart';
import 'package:productivity_sdk/src/common/application/run/maintenance_plant.dart';
import 'package:productivity_sdk/src/common/application/run/maintenance_templates.dart';
import 'package:productivity_sdk/src/common/application/run/task_run.dart';
import 'package:productivity_sdk/src/common/infrastructure/repositories/todo_repository_impl.dart';
import 'package:productivity_sdk/src/common/presentation/run/task_run_view.dart';
import 'package:productivity_sdk/src/common/presentation/tasks/task_card.dart';
import 'package:remixicon/remixicon.dart';

typedef TourAction = Future<void> Function(
    WidgetTester tester, StackRouter router);

class TourStep {
  const TourStep(this.key, this.settleMs, this.screenshot, this.action);

  final String key;
  final int settleMs;

  /// False for steps that only perform an action (no still captured).
  final bool screenshot;
  final TourAction action;
}

/// Runs once before the app is launched.
Future<void> tourSetup() async {
  // Pre-seed the language so the first-run language picker can never
  // block the tour behind a non-dismissible modal (the backend may
  // advertise several languages). LocalStorage.init() is idempotent -
  // app.main() calls it again.
  await LocalStorage.init();
  // Capture in dark mode: persist the same flag the in-app theme toggle
  // writes. AppNotifier reads it synchronously in its constructor (before
  // the first frame), so every still and reel starts dark.
  await LocalStorage.setAppThemeMode(true);
  if (LocalStorage.getLanguage() == null) {
    await LocalStorage.setLanguageData(LanguageData(
      id: '1',
      title: 'English',
      locale: 'en',
      backward: false,
      isDefault: true,
      active: true,
    ));
    await LocalStorage.setLanguageSelected(true);
    await LocalStorage.setLangLtr(false);
  }
}

final List<TourStep> tourSteps = <TourStep>[
  TourStep('welcome', 12000, true, (WidgetTester tester, StackRouter router) async {
    // wait: settle only.
  }),
  TourStep('auth_login', 5000, true, (WidgetTester tester, StackRouter router) async {
    // Land on /login (the welcome screen), then open the login sheet the
    // way a user does - via its Login button.
    router.replaceNamed('/login');
    await Future<void>.delayed(const Duration(seconds: 3));
    await tester.tap(
      find.text(AppHelpers.getTranslation(TrKeys.login)).first,
      warnIfMissed: false,
    );
  }),
  TourStep('auth_register', 5000, true, (WidgetTester tester, StackRouter router) async {
    // Close the login sheet, then open the register sheet from the
    // welcome screen's Register button.
    final NavigatorState navigator =
        tester.state(find.byType(Navigator).first);
    if (navigator.canPop()) {
      navigator.pop();
      await Future<void>.delayed(const Duration(seconds: 2));
    }
    await tester.tap(
      find.text(AppHelpers.getTranslation(TrKeys.register)).first,
      warnIfMissed: false,
    );
  }),
  TourStep('auth_reset_password', 5000, true, (WidgetTester tester, StackRouter router) async {
    // Close the register sheet, reopen the login sheet, then tap
    // "Forgot password" - its handler swaps the login sheet for the
    // reset-password sheet, exactly the path a user takes.
    final NavigatorState navigator =
        tester.state(find.byType(Navigator).first);
    if (navigator.canPop()) {
      navigator.pop();
      await Future<void>.delayed(const Duration(seconds: 2));
    }
    await tester.tap(
      find.text(AppHelpers.getTranslation(TrKeys.login)).first,
      warnIfMissed: false,
    );
    await Future<void>.delayed(const Duration(seconds: 3));
    await tester.tap(
      find.text(AppHelpers.getTranslation(TrKeys.forgotPassword)).first,
      warnIfMissed: false,
    );
  }),
  TourStep('auth_back_to_login', 3000, false, (WidgetTester tester, StackRouter router) async {
    final NavigatorState navigator =
        tester.state(find.byType(Navigator).first);
    // Bounded: at most one sheet is open, but stay safe against strays.
    for (int i = 0; i < 5 && navigator.canPop(); i++) {
      navigator.pop();
      await Future<void>.delayed(const Duration(milliseconds: 500));
    }
    router.replaceNamed('/login');
  }),
  TourStep('demo_sign_in', 6000, false, (WidgetTester tester, StackRouter router) async {
    final Element element = tester.element(find.byType(Navigator).first);
    final ProviderContainer container =
        ProviderScope.containerOf(element, listen: false);
    // loginProvider is autoDispose: hold a subscription so the notifier
    // survives between the field writes and the login call.
    final ProviderSubscription<dynamic> subscription =
        container.listen(loginProvider, (_, __) {});
    try {
      final login = container.read(loginProvider.notifier);
      login.setEmail('manager@demo.rokct.ai');
      login.setPassword('demo-learners-2026');
      // MockAuthRepository accepts any password, but the ADDRESS decides the
      // role it hands back (MockAuthRepository._demoRolesByEmail), and the
      // role decides whether this app's session_policy admits the session at
      // all. So each shell picks its own account with setup.demo_email in its
      // tour/app.tour.yaml; shells that leave it unset get the 'customer'
      // default. The timeout guards the post-session FCM sync, which can
      // stall on an emulator - navigation to the demo landing happens before
      // it, so a timeout is harmless.
      await login
          .login(element)
          .timeout(const Duration(seconds: 45), onTimeout: () {});
    } finally {
      subscription.close();
    }
  }),
  TourStep('back_to_login', 4000, false, (WidgetTester tester, StackRouter router) async {
    LocalStorage.logout();
    router.replaceNamed('/login');
  }),
  TourStep('manager_sign_in', 6000, false, (WidgetTester tester, StackRouter router) async {
    final Element element = tester.element(find.byType(Navigator).first);
    final ProviderContainer container =
        ProviderScope.containerOf(element, listen: false);
    // loginProvider is autoDispose: hold a subscription so the notifier
    // survives between the field writes and the login call.
    final ProviderSubscription<dynamic> subscription =
        container.listen(loginProvider, (_, __) {});
    try {
      final login = container.read(loginProvider.notifier);
      login.setEmail('manager@demo.rokct.ai');
      login.setPassword('demo-managers-2026');
      // MockAuthRepository accepts any credentials. The timeout guards the
      // post-session FCM sync, which can stall on an emulator - navigation
      // to the demo landing happens before it, so a timeout is harmless.
      await login
          .login(element)
          .timeout(const Duration(seconds: 45), onTimeout: () {});
    } finally {
      subscription.close();
    }
  }),
  TourStep('manager_home', 10000, false, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/main');
  }),
  TourStep('pos_scan', 8000, true, (WidgetTester tester, StackRouter router) async {
    // Select the POS tab (index 0) explicitly - an earlier fragment may
    // have left another tab selected, and mainProvider's selection
    // persists across routes.
    router.replaceNamed('/main');
    await Future<void>.delayed(const Duration(seconds: 3));
    final Element element = tester.element(find.byType(Navigator).first);
    final ProviderContainer container =
        ProviderScope.containerOf(element, listen: false);
    container.read(mainProvider.notifier).selectIndex(0);
  }),
  TourStep('pos_cart', 6000, true, (WidgetTester tester, StackRouter router) async {
    // Demo build: the barcode lane resolves through this SDK's
    // MockProductsRepository ("Flame-grilled beef burger", R150.00), zero backend
    // contact - the same path a real scan takes.
    final Element element = tester.element(find.byType(Navigator).first);
    final ProviderContainer container =
        ProviderScope.containerOf(element, listen: false);
    await container
        .read(posCartProvider.notifier)
        .addByBarcode('6001067890123');
    container.read(posCartProvider.notifier).increment(0);
  }),
  TourStep('pos_checkout', 8000, true, (WidgetTester tester, StackRouter router) async {
    // Continue (287, Key posContinue) sits at the foot of the cart -
    // the whole phone column, the cart plane at plane widths. Where the
    // till's PlaneHost grants more than one plane, Continue is the ONLY
    // way into the approved 11n checkout (it opens inside the planes;
    // BillingPage._openCheckout never pushes the route there), so the
    // branch reads the same plane count that method reads, from the
    // button's own context. One plane is the phone: the /pos-checkout
    // route, exactly the step this replaces.
    final Finder continueButton = find.byKey(const Key('posContinue'));
    final bool hostedInPlanes = continueButton.evaluate().isNotEmpty &&
        (Planes.maybeOf(tester.element(continueButton))?.count ?? 1) > 1;
    if (hostedInPlanes) {
      await tester.tap(continueButton, warnIfMissed: false);
    } else {
      router.replaceNamed('/pos-checkout');
    }
  }),
  TourStep('pos_receipt_preview', 6000, true, (WidgetTester tester, StackRouter router) async {
    // 293 on the checkout (merchants_sdk 1.29.0, frame 11k) opens the
    // receipt preview - the paper slip with the checkout's own dual
    // finish beneath it - pushed above /pos-checkout as a plain route
    // on the phone, handed to the till as the one-plane receipt (11r)
    // where the checkout is plane-hosted (see the pos_checkout step).
    // The button sits at the foot of the checkout's vertical scroll
    // column (one on a phone, the tender column on the planes spread),
    // and the sliver only builds it once it is in view, so every
    // vertical scrollable is run to its end first. The button carries
    // no widget key - its label is the tr_key the page itself renders.
    final Finder scrollables = find.byType(Scrollable);
    for (int i = 0; i < scrollables.evaluate().length; i++) {
      final ScrollableState scrollable =
          tester.state<ScrollableState>(scrollables.at(i));
      if (scrollable.position.axis != Axis.vertical) continue;
      scrollable.position.jumpTo(scrollable.position.maxScrollExtent);
    }
    await Future<void>.delayed(const Duration(seconds: 1));
    await tester.tap(
      find.text(AppHelpers.getTranslation(TrKeys.printReceipt)).first,
      warnIfMissed: false,
    );
  }),
  TourStep('pos_receipt_finish', 4000, false, (WidgetTester tester, StackRouter router) async {
    // "Print Receipt & Finish" (293) on the preview: print THEN record,
    // the checkout's own PosSaleFinish pipeline. Headless there is no
    // printer installed, so PosReceiptPrinter's default handler is a
    // no-op and the finish records through the demo PosOrdersFacade (in
    // memory, never the sync queue). A composed shell that installs a
    // hardware printer would fail the print here and leave the preview
    // up with the sale open - "Finish without Receipt" (294) then
    // records it, so the tour continues either way. On success the
    // preview pops and the checkout leaves with it, back to /main - on
    // the planes the receipt plane closes and the till spreads again.
    await tester.tap(
      find.byKey(const Key('posReceiptPrintFinish')),
      warnIfMissed: false,
    );
    await Future<void>.delayed(const Duration(seconds: 3));
    final Finder finishWithout =
        find.byKey(const Key('posReceiptFinishWithout'));
    if (finishWithout.evaluate().isNotEmpty) {
      await tester.tap(finishWithout, warnIfMissed: false);
    }
  }),
  TourStep('restaurant_hub', 8000, true, (WidgetTester tester, StackRouter router) async {
    // Land the manager home shell and select the restaurant tab (index 4
    // since merchants_sdk 1.14.0 - POS till 0, order queue 1, kitchen 2,
    // foods 3) through the shell's own mainProvider, the same state the
    // bottom-navigation buttons drive. Route first: an earlier fragment
    // may have left the app elsewhere, and mainProvider's selection
    // persists across routes.
    //
    // The tab is preload: false in the shell's IndexedStack, so selecting
    // it is what first builds RestaurantPage - whose initState fetches
    // the shop through SellerShopRepositoryFacade. In demo builds that is
    // this SDK's DemoSellerShopRepository (see the demo-grounding note at
    // the top of this file), so the header renders with the demo shop's
    // name and rating rather than empty; the rows below it carry their
    // own isDemo subtitles. The settle covers that first fetch.
    router.replaceNamed('/main');
    await Future<void>.delayed(const Duration(seconds: 3));
    final Element element = tester.element(find.byType(Navigator).first);
    final ProviderContainer container =
        ProviderScope.containerOf(element, listen: false);
    container.read(mainProvider.notifier).selectIndex(4);
  }),
  TourStep('sync_issues', 6000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/sync-issues');
  }),
  TourStep('menu', 8000, true, (WidgetTester tester, StackRouter router) async {
    // Land the manager home shell, then select the foods tab (index 3
    // since merchants_sdk 1.14.0 - POS till 0, order queue 1, kitchen 2;
    // this fragment had gone stale at 1 when the POS-first shift moved
    // foods to 2) through the shell's own mainProvider - the same state
    // the bottom navigation buttons drive. Route first: an earlier
    // fragment may have left the app elsewhere.
    router.replaceNamed('/main');
    await Future<void>.delayed(const Duration(seconds: 3));
    final Element element = tester.element(find.byType(Navigator).first);
    final ProviderContainer container =
        ProviderScope.containerOf(element, listen: false);
    container.read(mainProvider.notifier).selectIndex(3);
  }),
  TourStep('add_product', 6000, true, (WidgetTester tester, StackRouter router) async {
    // FoodsPage's own "+ New product" header button opens the
    // create-product modal (foods_page.dart's _newButton dispatches by
    // inner tab, foods sub-tab 0 - the shell FAB's old rule, moved
    // in-page in products_sdk 1.6.0). Both its wide (labelled) and
    // phone (icon ring) dresses carry Remix.add_line, the only
    // Remix.add_line on this screen; tolerant tap anyway.
    await tester.tap(
      find.byIcon(Remix.add_line).first,
      warnIfMissed: false,
    );
  }),
  TourStep('add_product_close', 3000, false, (WidgetTester tester, StackRouter router) async {
    final NavigatorState navigator =
        tester.state(find.byType(Navigator).first);
    // Bounded: at most the one modal sheet is open.
    for (int i = 0; i < 3 && navigator.canPop(); i++) {
      navigator.pop();
      await Future<void>.delayed(const Duration(milliseconds: 500));
    }
  }),
  TourStep('order_queue', 8000, true, (WidgetTester tester, StackRouter router) async {
    // Land the manager home shell and select the order-queue tab
    // (index 1 - index 0 is the POS till since merchants_sdk 1.12.0)
    // explicitly - an earlier fragment may have left another tab
    // selected, and mainProvider's selection persists across routes.
    router.replaceNamed('/main');
    await Future<void>.delayed(const Duration(seconds: 3));
    final Element element = tester.element(find.byType(Navigator).first);
    final ProviderContainer container =
        ProviderScope.containerOf(element, listen: false);
    container.read(mainProvider.notifier).selectIndex(1);
  }),
  TourStep('order_history', 6000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/order-history');
  }),
  TourStep('kitchen_queue', 8000, true, (WidgetTester tester, StackRouter router) async {
    // Land the manager home shell and select the Kitchen tab (index 2
    // since merchants_sdk 1.14.0 - the POS till is 0, the order queue 1)
    // explicitly - an earlier fragment may have left another tab
    // selected, and mainProvider's selection persists across routes.
    router.replaceNamed('/main');
    await Future<void>.delayed(const Duration(seconds: 3));
    final Element element = tester.element(find.byType(Navigator).first);
    final ProviderContainer container =
        ProviderScope.containerOf(element, listen: false);
    container.read(mainProvider.notifier).selectIndex(2);
  }),
  TourStep('comms_language', 6000, true, (WidgetTester tester, StackRouter router) async {
    // Open the language sheet the way the app's own screens do: the same
    // AppHelpers.showCustomModalBottomSheet call auth's login page and
    // marketplace's profile use for EmbeddedWidgets.I.languageScreen.
    // LanguageScreen is comms_sdk's own widget; in demo builds its list
    // comes from MockSettingsRepository.getLanguages(). The sheet follows
    // the theme the tour is running in (the shells set it in setup), so
    // the still never captures a light sheet inside a dark tour.
    final BuildContext sheetContext =
        tester.element(find.byType(Navigator).first);
    AppHelpers.showCustomModalBottomSheet(
      context: sheetContext,
      modal: LanguageScreen(
        onSave: () =>
            Navigator.of(sheetContext, rootNavigator: true).pop(),
      ),
      isDarkMode: LocalStorage.getAppThemeMode(),
    );
  }),
  TourStep('comms_language_close', 3000, false, (WidgetTester tester, StackRouter router) async {
    // Tolerant: pop only when the sheet from the step above is actually
    // on screen, so this can never pop a real app route.
    if (find.byType(LanguageScreen).evaluate().isNotEmpty) {
      final NavigatorState navigator =
          tester.state(find.byType(Navigator).first);
      if (navigator.canPop()) {
        navigator.pop();
      }
    }
  }),
  TourStep('revenue_income', 8000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/income');
  }),
  TourStep('subscriptions_plans', 8000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/subscriptions');
  }),
  TourStep('productivity_tasks', 7000, true, (WidgetTester tester, StackRouter router) async {
    final DateTime today = DateTime.now();
    DateTime at(int days, int hour) =>
        DateTime(today.year, today.month, today.day + days, hour);
    String ago(int hours) =>
        today.subtract(Duration(hours: hours)).toIso8601String();
    await TodoRepositoryImpl(AppDatabase()).saveTodos(
      <Map<String, dynamic>>[
        <String, dynamic>{
          'id': 'tour-task-depot-01',
          'notifId': 47101,
          'title': 'Deliver 40 × 20 L to the Mokopane depot',
          'isDone': false,
          'deadline': at(1, 9).toIso8601String(),
          'reminder': true,
          'priority': 'High',
          'category': 'Deliveries',
          'recurrence': 'Weekly',
          'createdAt': ago(2),
          'subtasks': <Map<String, dynamic>>[
            <String, dynamic>{'title': 'Load the bakkie', 'isDone': true},
            <String, dynamic>{
              'title': 'Collect the signed delivery note',
              'isDone': false,
            },
            <String, dynamic>{'title': 'Bring back the empties', 'isDone': false},
          ],
        },
        <String, dynamic>{
          'id': 'tour-task-brine-02',
          'notifId': 47102,
          'title': 'Order brine salt · 25 kg bags',
          'isDone': false,
          'deadline': at(2, 10).toIso8601String(),
          'reminder': false,
          'priority': 'Medium',
          'category': 'Plant',
          'recurrence': 'Monthly',
          'createdAt': ago(5),
          'subtasks': <Map<String, dynamic>>[
            <String, dynamic>{'title': 'Count the bags left', 'isDone': true},
            <String, dynamic>{'title': 'Send the order to the co-op', 'isDone': false},
          ],
        },
        <String, dynamic>{
          'id': 'tour-task-invoice-03',
          'notifId': 47103,
          'title': 'Chase the Polokwane Spar invoice',
          'isDone': false,
          'deadline': at(5, 12).toIso8601String(),
          'reminder': true,
          'priority': 'Low',
          'category': 'Admin',
          'recurrence': 'None',
          'createdAt': ago(9),
          'subtasks': <Map<String, dynamic>>[],
        },
        <String, dynamic>{
          'id': 'tour-task-borehole-04',
          'notifId': 47104,
          'title': 'Second borehole · quotes and water-use licence',
          'isDone': false,
          'reminder': false,
          'priority': 'Medium',
          'category': 'Plant',
          'recurrence': 'None',
          'isLongTerm': true,
          'createdAt': ago(30),
          'subtasks': <Map<String, dynamic>>[
            <String, dynamic>{'title': 'Three drilling quotes', 'isDone': true},
            <String, dynamic>{'title': 'Water-use licence application', 'isDone': false},
            <String, dynamic>{'title': 'Pump and tank sizing', 'isDone': false},
          ],
        },
      ],
    );
    router.replaceNamed('/tasks');
    await Future<void>.delayed(const Duration(seconds: 3));
    final Finder card = find.byKey(
      const ValueKey<String>('task-card-tour-task-depot-01'),
    );
    if (card.evaluate().isNotEmpty) {
      await tester.tap(card.first, warnIfMissed: false);
    }
  }),
  TourStep('productivity_task_compose', 6000, true, (WidgetTester tester, StackRouter router) async {
    await MaintenancePlantStore.local.save(
      PlantRecord(
        megaCharVessels: 1,
        softenerVessels: 1,
        vesselsInstalledOn: DateTime(2026, 3, 14),
        preFilterInstalledOn: DateTime(2026, 8, 20),
        roFilterInstalledOn: DateTime(2026, 6, 1),
        postFilterInstalledOn: DateTime(2026, 6, 1),
        membranes: 2,
        membranesInstalledOn: DateTime(2026, 1, 10),
        recordedAt: DateTime.now(),
      ),
    );
    router.replaceNamed('/tasks');
    await Future<void>.delayed(const Duration(seconds: 3));
    final Finder compose = find.byKey(const ValueKey<String>('tasks-compose'));
    if (compose.evaluate().isNotEmpty) {
      await tester.tap(compose.first, warnIfMissed: false);
      await Future<void>.delayed(const Duration(seconds: 2));
    }
    final Finder softener = find.byKey(
      const ValueKey<String>('template-softener_maintenance'),
    );
    if (softener.evaluate().isNotEmpty) {
      await tester.tap(softener.first, warnIfMissed: false);
    }
  }),
  TourStep('productivity_maintenance_readings', 6000, true, (WidgetTester tester, StackRouter router) async {
    final DateTime now = DateTime.now();
    final Map<String, dynamic> task = MaintenanceTemplates.build(
      MaintenanceTemplate.softenerMaintenance,
      now: now,
    );
    task['id'] = 'tour-softener-sft-02';
    task['notifId'] = 47021;
    task['title'] = 'Softener SFT-02 · Polokwane plant';
    task['category'] = 'Plant';
    task['createdAt'] = now.toIso8601String();
    TaskRun run = TaskRun.fromTask(task);
    DateTime at = now.subtract(const Duration(hours: 1, minutes: 5));
    for (int i = 0; i < 9; i++) {
      run = run.start(i, at);
      at = at.add(Duration(seconds: run.steps[i].durationSeconds));
      run = run.complete(i, at);
    }
    await TodoRepositoryImpl(AppDatabase()).saveTodos(
      <Map<String, dynamic>>[run.applyTo(task)],
    );
    router.replaceNamed('/tasks');
    await Future<void>.delayed(const Duration(seconds: 3));
    final Finder runPill = find.descendant(
      of: find.byKey(const ValueKey<String>('task-card-tour-softener-sft-02')),
      matching: find.byKey(TaskCard.runKey),
    );
    if (runPill.evaluate().isNotEmpty) {
      await tester.tap(runPill.first, warnIfMissed: false);
      await Future<void>.delayed(const Duration(seconds: 3));
    }
    final Finder resume = find.byKey(TaskRunView.resumeKey);
    if (resume.evaluate().isNotEmpty) {
      await tester.tap(resume.first, warnIfMissed: false);
      await Future<void>.delayed(const Duration(seconds: 1));
    }
    const List<String> readings = <String>['175', '212', '8.4', '1.9'];
    for (int i = 0; i < readings.length; i++) {
      final Finder field = find.byKey(TaskRunView.readingKey(i));
      if (field.evaluate().isNotEmpty) {
        await tester.enterText(field.first, readings[i]);
        await tester.pump();
      }
    }
  }),
  TourStep('productivity_maintenance_photo', 6000, true, (WidgetTester tester, StackRouter router) async {
    final Finder permeate = find.byKey(TaskRunView.readingKey(1));
    if (permeate.evaluate().isNotEmpty) {
      await tester.enterText(permeate.first, '40');
      await tester.pump();
    }
    final Finder forward = find.byKey(TaskRunView.continueKey);
    if (forward.evaluate().isNotEmpty) {
      await tester.tap(forward.first, warnIfMissed: false);
    }
  }),
  TourStep('calc_keypad', 6000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/calc');
  }),
];
