// Copyright (c) 2026 ROKCT INTELLIGENCE (PTY) LTD
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.


///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String assetsImagesUi3 = 'assets/images/ui3.png';
  static const String imagesAppLogo = 'assets/images/app_logo.png';
  static const String imagesDelivery = 'assets/images/delivery.png';
  static const String imagesDoor = 'assets/images/door.png';
  static const String imagesFast = 'assets/images/fast.png';
  static const String imagesLogo = 'assets/images/logo.png';
  static const String imagesNotFound = 'assets/images/notFound.png';
  static const String imagesSave = 'assets/images/save.png';
  static const String imagesSet = 'assets/images/set.png';
  static const String imagesSplash = 'assets/images/splash.png';
  static const String imagesSplash1 = 'assets/images/splash1.png';
  static const String imagesUi0 = 'assets/images/ui0.png';
  static const String imagesUi1 = 'assets/images/ui1.png';
  static const String imagesUi2 = 'assets/images/ui2.png';
  static const String imagesUi3 = 'assets/images/ui3.png';
  static const String imagesVisa = 'assets/images/visa.png';
  static const String lottieGirlEmpty = 'assets/lottie/girl_empty.json';
  static const String lottieNotFound = 'assets/lottie/not-found.json';
  static const String lottieNotFoundPage = 'assets/lottie/not_found_page.json';
  static const String lottieProcessing = 'assets/lottie/processing.json';
  static const String svgsAdress = 'assets/svgs/adress.svg';
  static const String svgsAvatar = 'assets/svgs/avatar.svg';
  static const String svgsContact = 'assets/svgs/contact.svg';
  static const String svgsDelivery = 'assets/svgs/delivery.svg';
  static const String svgsDelivery2 = 'assets/svgs/delivery2.svg';
  static const String svgsDeliveryTime = 'assets/svgs/delivery_time.svg';
  static const String svgsDiscount = 'assets/svgs/discount.svg';
  static const String svgsEmpty = 'assets/svgs/empty.svg';
  static const String svgsFilter = 'assets/svgs/filter.svg';
  static const String svgsOrderTime = 'assets/svgs/orderTime.svg';
  static const String svgsPickUpFrom = 'assets/svgs/pickUpFrom.svg';
  static const String svgsStar = 'assets/svgs/star.svg';
  static const String svgsTicket = 'assets/svgs/ticket.svg';
}
